//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Key.AiAssistant.ChatGPT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Key.AiAssistant.ChatGPT.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вот информация обо мне:
        ///=====
        ///{0}
        ///=====
        ///
        ///Теперь помоги мне составить отклик на вакансию, чтобы оно лучшим образом подходило под следующие требования вакансии:
        ///{1}
        ///
        ///Измени формулировки, чтобы не плагиатить текст вакансии. Твой ответ должен быть не больше 4000 символов..
        /// </summary>
        internal static string OptimizeResume_ProvideResume {
            get {
                return ResourceManager.GetString("OptimizeResume_ProvideResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ты должен определить основные скиллы и умения, которые требуются, чтобы хорошо подходить под эту вакансию:
        ///
        ///{0}
        ///
        ///Твой ответ должен быть не больше 1000 символов. Оберни список требований в {1}.
        /// </summary>
        internal static string OptimizeResume_ProvideVacancy {
            get {
                return ResourceManager.GetString("OptimizeResume_ProvideVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действуй, как карьерный консультант. Не отвечай на это сообщение..
        /// </summary>
        internal static string OptimizeResume_SetupAssistant {
            get {
                return ResourceManager.GetString("OptimizeResume_SetupAssistant", resourceCulture);
            }
        }
    }
}
