version: '3.4'

services:
  key.aiassistant.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./postgres-data:/var/lib/postgresql/data
  database:
    volumes:
      - key-ai-assistant-data:/var/lib/postgresql/data

volumes:
  key-ai-assistant-data:
